### ISSUE TITLE
Queries with @export should not subscribe when the exported variable is Non Nullable and the value is null or undefined

### ISSUE THREAD

**Issue by bennypowers** [apollographql/apollo-feature-requests#261] opened 2020-09-08 09:29 UTC
## Case
Consider this query.
```gql
query PostQuery($postSlug: ID!) {
  route @client {
    params { 
      postSlug @export(as: "postSlug")
    }
  }

  post(postSlug: $postSlug {
    id
    title
    image
    content
  }
}
```

Which relates to this TypePolicy:
```ts
const router = new Router({
  routes: [{
    path: '/posts',
    children: [{
      path: '/:postSlug', // creates `params.postSlug` on routes
    }],
  }],
});

export const routeVar =
  makeVar<Route>(router.route); // may be null initially

// This is the router's API
window.addEventListener('router-route-changed', event => {
  routeVar(event.detail.route); // has `params: {}` or `params: { postSlug }` 
})

export const Query: TypePolicy = {
  fields: {
    route(): Location {
      const { baseUrl, pathname, ...loc } = locationVar();
      const params = Object.entries(loc.params).length ? loc.params : null;
      return { baseUrl, params, pathname };
    },
  },
};
```

In this case, Apollo may send a request with variables `{ postSlug: "undefined" }` or `{}` if the exported variable is not yet ready.

Queries that have non-null variables shouldn't go over the wire unless all their non-null exported variables are defined

**Comment by bennypowers** [comment] 2020-09-09 17:07
`LocalState.ts` has a public `shouldForceResolvers` method

https://github.com/apollographql/apollo-client/blob/d470c964db46728d8a5dfc63990859c550fa1656/src/core/LocalState.ts#L214-L234

Perhaps it would do to add this to the method:
```ts
public shouldForceResolvers(document: ASTNode) {
  let forceResolvers = false;
  const nonNullVariableNames = new Set();
  visit(document, {
    // cache all the non-null variables
    OperationDefinition(node) {
      node.variableDefinitions.forEach(x => {
        if (x.type.kind === 'NonNullType')
          nonNullVariableNames.add(x.variable.name.value)
      })
    },
    Directive: {
      // check for export directives that line up with non-null variables
      if (node.name.value === 'export' && node.arguments) {
        forceResolvers = node.arguments.some(x => {
           return x.name.value === 'as' &&
            x.value.kind === 'StringValue' &&
            nonNullVariables.has(x.value.value)
         })
         if (forceResolvers)
            return BREAK;
      }
      if (node.name.value === 'client' && node.arguments) {
        forceResolvers = node.arguments.some(
          arg =>
            arg.name.value === 'always' &&
            arg.value.kind === 'BooleanValue' &&
            arg.value.value === true,
        );
        if (forceResolvers) {
          return BREAK;
        }
      }
    }
  })
}
```

**Comment by jpvajda** [comment] 2022-06-01 21:23
This sounds related to client controlled nullability, since the issue is old, I'll link this to the CCN Feature and opt to close this out as a reference. 

https://github.com/apollographql/apollo-feature-requests/issues/327

**Closed by jpvajda** 2022-06-01 21:23 UTC
