### ISSUE TITLE
Provide a TTL (time to live) cache mechanism

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-feature-requests#361] opened 2022-11-10 18:05 UTC
To help provide better support for Apollo Client caching strategy that uses TTLs. We are considering offering a `fetchPolicy` that would allow a user to set a TTL value or some other cache control mechanism that can use a TTL value for caching.

As a workaround we've recommended to create a read/merge function for our type that enriches the object with a timestamp on merge and then determine the time elapsed on read. If it is greater than the TTL you'd then schedule cache eviction and refetch the data.

This was a clever idea however some users are reporting issues with this approach:

_After the first two read calls and merge call neither function is called again. Even when the page is unmounted and remounted the read function would no longer be called after the first couple times. This happens regardless of time elapsed and is reproducible by including a log statement and unconditionally returning the object from the read function._ 

Relates to: https://github.com/apollographql/apollo-kotlin/issues/3566#issuecomment-1144746346

**Comment by jerelmiller** [comment] 2023-08-29 17:14
Closing this as a duplicate of #336. Will track this request in #336 instead.

**Closed by jerelmiller** 2023-08-29 17:14 UTC
Labels: project-apollo-client, 📕 cache
