### ISSUE TITLE
Add a way to strip __typename field from query and mutation results

### ISSUE THREAD

**Issue by vladshcherbin** [apollographql/apollo-feature-requests#6] opened 2018-07-27 17:58 UTC
Migrated from: apollographql/apollo-client#1564

**Comment by smeijer** [comment] 2018-08-31 14:29
Isn't this whats `filter` from `graphql-anywhere` is about?

https://www.apollographql.com/docs/react/advanced/fragments.html#filtering-with-fragments

**Comment by vladshcherbin** [comment] 2018-08-31 22:54
@smeijer not really. It's the same as [addTypename](https://www.apollographql.com/docs/react/advanced/caching.html#configuration) but per query or mutation instead of a global one.

**Comment by 27percent** [comment] 2018-10-01 09:42
This is really killing us right now and it'd be a huge help if this functionality was built into apollo

**Comment by RadAcademy** [comment] 2018-10-10 12:57
For anyone using Angular, I am currently using this middleware which strips the '__typename' off all requests. It has come in very handy for me. perhaps someone else would benefit.

`
import { ApolloLink } from 'apollo-link';

export class AppModule {

  constructor(private httpLink: HttpLink, private apollo: Apollo) {

    const http = httpLink.create({ 
      uri: environment.graphqlLink,
      withCredentials: true
    });

    const typenameMiddleware = new ApolloLink((operation, forward) => {
      if (operation.variables) {
        operation.variables = JSON.parse(JSON.stringify(operation.variables), this.omitTypename)
      }
      return forward(operation)
    });
    
    const myAppLink = ApolloLink.from([typenameMiddleware, http]);
    apollo.create({
      link: myAppLink, 
      cache: new InMemoryCache()
    });

  }

  private omitTypename(key, value) {
    return key === '__typename' ? undefined : value
  }

}
`

**Comment by nvuhung** [comment] 2018-10-27 08:57
> For anyone using Angular, I am currently using this middleware which strips the '__typename' off all requests. It has come in very handy for me. perhaps someone else would benefit.
> 
> `
> import { ApolloLink } from 'apollo-link';
> 
> ```
>    export class AppModule {
> 
>   constructor(private httpLink: HttpLink, private apollo: Apollo) {
> 
>     const http = httpLink.create({ 
>       uri: environment.graphqlLink,
>       withCredentials: true
>     });
> 
>     const typenameMiddleware = new ApolloLink((operation, forward) => {
>       if (operation.variables) {
>         operation.variables = JSON.parse(JSON.stringify(operation.variables), this.omitTypename)
>       }
>       return forward(operation)
>     });
>     
>     const myAppLink = ApolloLink.from([typenameMiddleware, http]);
>     apollo.create({
>       link: myAppLink, 
>       cache: new InMemoryCache()
>     });
>     }
>     private omitTypename(key, value) {
>       return key === '__typename' ? undefined : value
>     }
>   }
> ```
> `

This solution will be failed if you upload file. The file will be converted to object ({}) after use JSON.parse.

**Comment by gihrig** [comment] 2018-11-04 19:00
Working with Apollo cache in JS outside of React I ran into this issue. For some reason none of the suggested fixes worked for me. Maybe that's because I have a deeply nested data structure and to accommodate that I use Fragments.

In JS, stripping `__typename` turned out to be fairly easy. After some trial and error, I came up with this:

```javascript
  // Deep copy of uiParent
  const uiParentCleaned = JSON.parse(JSON.stringify(uiParent))

  // Strip __typename from uiParent and item list
  delete uiParentCleaned.__typename
  uiParentCleaned.items.map((item) => (
    // eslint-disable-next-line no-param-reassign
    delete item.__typename
  ))
```

**Comment by RealSilo** [comment] 2019-02-08 04:42
Any updates here?

**Comment by djmgh** [comment] 2019-02-09 05:27
Please add this functionality. Super frustrating this is an issue.

**Comment by matteo-hertel** [comment] 2019-02-09 19:17
For all the people using the `JSON.parse approach` like https://github.com/apollographql/apollo-client/issues/1564#issuecomment-357492659 or https://github.com/apollographql/apollo-feature-requests/issues/6#issuecomment-428560796 a word of caution: if there is anything that is not a JS primitive like a File or a Blob , that will be removed (as in cast to the closest stringifiable value like {}) and never be sent as part of the graphQl call and File Upload for instance won't work anymore, this was the cause of a bad afternoon for me so hopefully you won't find yourself in this situation 😄

**Comment by casto101** [comment] 2019-02-19 20:46
We ran into the exact same issue today @matteo-hertel. Out of curiosity, what did you end up doing to get around it? We have a deeply nested structure and it feels very icky to drill into it to avoid stringifying the File.

**Comment by matteo-hertel** [comment] 2019-02-19 20:53
I've sticked togheter a function to deeply remove the typename and making sure I'm not touching the File object
```
function stripTypenames(obj: any, propToDelete: string) {
  for (const property in obj) {
    if (typeof obj[property] === 'object' && !(obj[property] instanceof File)) {
      delete obj.property;
      const newData = stripTypenames(obj[property], propToDelete);
      obj[property] = newData;
    } else {
      if (property === propToDelete) {
        delete obj[property];
      }
    }
  }
  return obj;
}
```

and added it as middleware

```
const removeTypenameMiddleware = new ApolloLink(
  (operation: OperationInterface, forward: ()=>voil | null) => {
    if (operation.variables) {
      operation.variables = stripTypenames(operation.variables, '__typename');
      return forward ? forward(operation) : null;
    }
  },
);

```
it worked quite well but I'm not 100% happy with it

**Comment by lukejagodzinski** [comment] 2019-04-08 16:57
It's frustrating that this feature is still not implemented. It isn't big of a deal for flat structures but if you have nested objects then it's really annoying to have to remove all the `__typename`s. There should be an option to remove `__typename`s when querying. From what I understand `__typename` is only necessary to properly identify types in the cache

**Comment by fbartho** [comment] 2019-04-08 17:46
@lukejagodzinski When working with a `union` you need something like the `__typename` to act as a discriminant so you know what nested object you're working with. So that's not a feature you *always* want.

**Comment by gihrig** [comment] 2019-04-08 18:11
> @fbartho So that's not a feature you always want.

No argument there. But it would sure be nice to have a simple documented way to eliminate `__typename` when it gets in the way. Or even better, to automatically do the necessary parameter modifications so it becomes a non-issue for all devs.

As I recall, I spent a few days wrestling with this issue before I got it settled.

**Comment by freshcoat** [comment] 2019-04-15 11:00
Removing the __typename shouldn’t be the way to go as if’s important to keep the cache in sync (cache uses the typenames). I am using the ‘omit’ function of lodash to remove the typename from the object before doing an mutation, this works great for us.

**Comment by lukejagodzinski** [comment] 2019-04-15 11:35
@freshcoat no one talks about removing `__typename` from the cache. We just would like to have an option to not fetch it from the cache or at least remove it automatically when sending to mutation. That's it

**Comment by RyannGalea** [comment] 2019-04-15 11:51
You are able to change what the cache uses for an ID also, instead of '__typename'.

**Comment by elie222** [comment] 2019-07-09 13:40
Why does the mutation care if there are additional fields in `variables` at all? Can't Apollo Client just use the fields it needs and filter out the rest?

**Comment by RyannGalea** [comment] 2019-07-10 05:14
In most cases @elie222 the '__typename' is not something we include in our inputs, therefore when the mutation is sent to the server along with a '__typename' automatically it doesn't match the shape of our input which is causing issues.

**Comment by elie222** [comment] 2019-07-10 09:18
@RyannGalea I understand the issue. I'm saying that in general, whether the extra field is called `__typename`, `extraType` or anything else, it should be stripped from the request. I ran into this issue myself that there was an extra `id` field for a mutation I was making. I had to strip this field myself.

**Comment by ackvf** [comment] 2019-09-18 18:04
The middleware solution isn't working for me. Why there is no `__typename` field within the operations.variables.

**Comment by phjardas** [comment] 2019-10-17 17:18
A nice solution would be to make the `__typename` field invisible to JSON serialization. A classic way to add metadata to objects is to use a symbol as the property key, which makes the property automatically non-enumerable.

```javascript
const obj = { hello: "world" }
const typenameSymbol = Symbol("apolloTypename")
Object.defineProperty(obj, typenameSymbol, { value: "Test" })

console.log(obj)
// --> { hello: 'world' }

console.log(JSON.stringify(obj))
// --> {"hello":"world"}

console.log(obj[typenameSymbol])
// --> Test
```

**Comment by CanRau** [comment] 2019-10-17 19:19
+1 for symbols sounds great :+1:

**Comment by dafrie** [comment] 2019-11-11 10:23
In case someone needs stripping only for firing of mutations and not on each query/subscription (in TypeScript):

```ts
import { GraphQLError, OperationDefinitionNode } from "graphql";
import { getMainDefinition } from "apollo-utilities";

const cleanTypenameLink = new ApolloLink((operation, forward) => {
  const omitTypename = (key: any, value: any) =>
    key === "__typename" ? undefined : value;

  const def = getMainDefinition(operation.query); 
  if (def && (<OperationDefinitionNode>def).operation === "mutation") {
    operation.variables = parse(stringify(operation.variables), omitTypename);
  }
  return forward ? forward(operation) : null;
});
```

**Comment by joshuarobs** [comment] 2019-12-30 06:52
Why is this still not implemented? We need QoL for the development process please

**Comment by Hale-ma** [comment] 2020-01-16 12:34
I run into this issue too. Unluckily the v2.6 client set the object to strict mode. This means it is even not possible to delete __typename "in-place" . A copy of the origin object is required to delete __typename.

**Comment by HosseinAgha** [comment] 2020-01-18 18:45
Dear @hwillson and @benjamn,  

I'm mentioning you here as I think you are currently the most active maintainers of the Apollo Client.  
I think the livelihood of an open-source project is not only determined by the number of its contributors or its Github stars but it is also determined by how its maintainers participate in the community discussions.  

I couldn't find any maintainers response in this issue and some other issues with high number of community reactions.  

Leaving a _PRs welcome_ comment and guiding the community on how to contribute this feature, or even rejecting it altogether because of some architectural decisions, ensures us that this project is alive and community voice is being heard.  

Thank you for this awesome tool.

**Comment by nik-lampe** [comment] 2020-01-21 13:42
The solution provided by @dafrie  does work, but can cause problems when you have non serializable objects in your payload. In my case I'm uploading files in my mutation. These File Objects get stripped out to only include the pathname.

I have adapted it to use omit-deep-lodash to prevent this.

```

import omitDeep from 'omit-deep-lodash'

const cleanTypenameLink = new ApolloLink((operation, forward) => {
  const keysToOmit = ['__typename', 'createdAt', 'updatedAt']

  const def = getMainDefinition(operation.query)
  if (def && def.operation === 'mutation') {
    operation.variables = omitDeep(operation.variables, keysToOmit)
  }
  return forward ? forward(operation) : null
})
```

**Comment by aharasta** [comment] 2020-02-12 03:30
@nik-lampe Thanks for the workaround, not ideal that this is necessary, but seems to be working nicely!

**Comment by andrewmclagan** [comment] 2020-04-15 01:47
Our team is migrating to Apollo, this is a show-stopper. 

Not because of the issue, simply because of the lack of any meaningful response on such a large issue in such a long period. It has dropped our confidence level that Apollo is actually being maintained.

**Comment by RyannGalea** [comment] 2020-04-15 02:25
> upload file

This is what I do to the avoid issues with my file upload integration.

```
  const typenameLink = new ApolloLink((operation, forward) => {
    if (operation.variables) {
      let { fileInput, ...others } = operation.variables
      others = omitDeep(JSON.parse(JSON.stringify(others)), ['__typename'])
      const { input } = others
      operation.variables = {
        input: RemoveNullValues(input),
        fileInput,
        ...others
      }
    }
    return forward(operation)
  })
```

**Comment by RyannGalea** [comment] 2020-04-15 02:26
> > For anyone using Angular, I am currently using this middleware which strips the '__typename' off all requests. It has come in very handy for me. perhaps someone else would benefit.
> > `
> > import { ApolloLink } from 'apollo-link';
> > ```
> >    export class AppModule {
> > 
> >   constructor(private httpLink: HttpLink, private apollo: Apollo) {
> > 
> >     const http = httpLink.create({ 
> >       uri: environment.graphqlLink,
> >       withCredentials: true
> >     });
> > 
> >     const typenameMiddleware = new ApolloLink((operation, forward) => {
> >       if (operation.variables) {
> >         operation.variables = JSON.parse(JSON.stringify(operation.variables), this.omitTypename)
> >       }
> >       return forward(operation)
> >     });
> >     
> >     const myAppLink = ApolloLink.from([typenameMiddleware, http]);
> >     apollo.create({
> >       link: myAppLink, 
> >       cache: new InMemoryCache()
> >     });
> >     }
> >     private omitTypename(key, value) {
> >       return key === '__typename' ? undefined : value
> >     }
> >   }
> > ```
> > 
> > 
> > `
> 
> This solution will be failed if you upload file. The file will be converted to object ({}) after use JSON.parse.

This is what I do to the avoid issues with my file upload integration.

```
  const typenameLink = new ApolloLink((operation, forward) => {
    if (operation.variables) {
      let { fileInput, ...others } = operation.variables
      others = omitDeep(JSON.parse(JSON.stringify(others)), ['__typename'])
      const { input } = others
      operation.variables = {
        input: RemoveNullValues(input),
        fileInput,
        ...others
      }
    }
    return forward(operation)
  })
```

**Comment by rmoutray-configureone** [comment] 2020-04-15 10:22
I understand the struggles here and pragmatism, but the approach that causes these problems - sending output types back as inputs - seems to go against the GraphQL specification as well as any hope of command query responsibility segregation (CQRS) and truly type-safe operations.

"Input Object types can only be used as input types. Object, Interface, and Union types can only be used as output types."

https://spec.graphql.org/June2018/#sec-Input-and-Output-Types

Also some good reading: https://stackoverflow.com/a/55881719

**Comment by chitown35** [comment] 2020-04-15 10:25
I understand the struggles here and pragmatism, but the approach that causes these problems - sending output types back as inputs - seems to go against the GraphQL specification as well as any hope of command query responsibility segregation (CQRS) and truly type-safe operations.

"Input Object types can only be used as input types. Object, Interface, and Union types can only be used as output types."

https://spec.graphql.org/June2018/#sec-Input-and-Output-Types

Also some good reading: https://stackoverflow.com/a/55881719

**Comment by weeksie** [comment] 2020-04-27 15:14
This has been open for _years_, guys. come on.

**Comment by andrewmclagan** [comment] 2020-04-28 05:00
In their defence, this is a problem faced by all GQL client implementations. see urql etc.

**Comment by weeksie** [comment] 2020-04-28 19:17
That's fair. I was also in a shit mood yesterday. I ended up using a variation of the middleware link and sorted it out. My snide comment aside, I do think that this pretty poor developer ergonomics for an exceedingly common problem. 

But hey, open source, etc etc and I'm quite happy to have and use the library and appreciate the work the maintainers have done on it.

**Comment by andrewmclagan** [comment] 2020-04-30 05:23
haha yes... well I do agree there are allot of issues with Apollo docs that have cost us huuuuge amounts of time. But than again we dont really contribute either.

**Comment by Mottoweb** [comment] 2020-05-08 05:44
Would be great to have this, doing it manually until then :/

**Comment by AndyDeNike** [comment] 2020-05-09 22:34
I for one would like to say F __typename implementation.  @Mottoweb @everybodyelse what is the optimal way of removing __typename manually, at the moment?

**Comment by Mottoweb** [comment] 2020-05-10 06:05
@AndyDeNike I am doing a copy and then `delete obj.__typename`

My case may be different though, I am getting an array of objects and then need to update it in local state and mutate on submit.

**Comment by lukeramsden** [comment] 2020-05-11 14:46
Just put this on the exceedingly long list of issues and tribal knowledge required in modern web development. GitHub issues are as good as docs!

**Comment by davewasmer** [comment] 2020-05-11 15:21
Here's what I use, in case it's helpful for anyone else (uses lodash). The Typescript annotations aren't perfect (it only recognizes the omitted `__typename` one level deep) but I've found it good enough for my use cases so far:

```
import { isPlainObject, isArray } from 'lodash';

export default function cloneWithoutTypename<T>(obj: T): Omit<T, '__typename'> {
  if (!isPlainObject(obj)) {
    return obj;
  }
  let result: any = {};
  for (let key in obj) {
    if (key === '__typename') {
      continue;
    }
    let value = (obj as any)[key];
    if (isPlainObject(value)) {
      result[key] = cloneWithoutTypename(value);
    } else if (isArray(value)) {
      result[key] = value.map(cloneWithoutTypename);
    } else {
      result[key] = value;
    }
  }
  return result;
}

```

**Comment by stvdrsch** [comment] 2020-06-25 13:09
I had this code for months in my project but I ran into an error when doing the Upload of a File object (with `ReactNativeFile` of `apollo-upload-client`). When using the `omitDeep` or the many of the Apollolinks here provided the `ReactNativeFile` object is transformed to a regular object. Causing your backend to probably not accept the object for upload.

Just a comment on this issue as it can have this as a result and hopefully prevent some lost hours of my colleague-developers.

**Comment by sebdec** [comment] 2020-07-16 18:39
@stvdrsch 

It's what I use to handle file imports:
```
// Used to remove typename property from objects
const isFile = value =>
  (typeof File !== 'undefined' && value instanceof File) || (typeof Blob !== 'undefined' && value instanceof Blob);

// From https://gist.github.com/Billy-/d94b65998501736bfe6521eadc1ab538
const omitDeep = (value, key) => {
  if (Array.isArray(value)) {
    return value.map(i => omitDeep(i, key));
  } else if (typeof value === 'object' && value !== null && !isFile(value)) {
    return Object.keys(value).reduce((newObject, k) => {
      if (k === key) return newObject;
      return Object.assign({ [k]: omitDeep(value[k], key) }, newObject);
    }, {});
  }
  return value;
};

const omitTypenameLink = new ApolloLink((operation, forward) => {
  if (operation.variables) {
    operation.variables = omitDeep(operation.variables, '__typename');
  }
  return forward(operation);
});
```

**Comment by MichaelHindley** [comment] 2020-07-24 17:12
Hello, landed here due to functionality testing of Prisma 2 and type-graphql, for the purpose of spreading awareness about this behaviour between the projects and developers working with apollo-server+client, here is a link to the discussion: https://github.com/MichalLytek/type-graphql/issues/476#issuecomment-663639646

**Comment by joncursi** [comment] 2020-08-06 13:53
Here's a workaround, using `clone-deep` and `omit-deep` NPM packages:

```
import cloneDeep from 'clone-deep';
import omitDeep from 'omit-deep';

...

const someObject = data.someObject; // data comes from Query component or useQuery hoook

await someMutation({
  variables: {
    ...
    someObject: omitDeep(cloneDeep(someObject), '__typename'),
    ...
  },
});
```

**Comment by RyannGalea** [comment] 2020-08-13 04:15
My integration recently broke when I upgraded to v3, any idea on why?

**Comment by Almaju** [comment] 2020-08-20 02:51
This is the first link when you search on Google. There is actually a good answer there: https://stackoverflow.com/questions/47211778/cleaning-unwanted-fields-from-graphql-responses/51380645#51380645

Quick workaround is:

```js
apollo.create({
  link: http,
  cache: new InMemoryCache({
    addTypename: false
  })
});
```

**Comment by anthonysapien** [comment] 2020-09-19 15:34
FWIW, I used fetchPolicy: 'no-cache' on the query for data to be mutated. This at least makes the object mutable so you can delete the __typename entries without deep cloning.

**Comment by Almaju** [comment] 2020-10-06 18:37
> Not sure if anyone suggested this but it seemed to work for me
> 
> ```
> apollo.create({
>   link: http,
>   cache: new InMemoryCache({
>     addTypename: false
>   })
> });
> ```
> 
> ```
> const httpLink = createHttpLink({
>  uri: process.env.REACT_APP_GRAPH_ENDPOINT,
>   credentials: 'include'
> });
> 
> const middlewareLink = new ApolloLink((operation, forward) => {
>   operation.setContext({
>     headers: {
>       accessToken: localStorage.getItem('x-access-token') || null,
>       refreshToken: localStorage.getItem('x-refresh-token') || null
>     }
>   });
> 
>   return forward(operation);
> });
> 
> const link = middlewareLink.concat(httpLink);
> 
> const client = new ApolloClient({
>   cache: new InMemoryCache(({
>     addTypename: false
>   })),
>   link
> });
> ```
> 
> My whole example looks like the above and the **___typename_** is no longer present for me
> Not my solution but pulled from [here](https://stackoverflow.com/questions/47211778/cleaning-unwanted-fields-from-graphql-responses/51380645#51380645

I don't recommend that because you might break the cache.

**Comment by Stradivario** [comment] 2020-10-20 17:40
Another thing that we break removing `__typename` is Unions since there is no way of knowing the type of the Union unless you check `__typename`.

**Comment by aminnoura** [comment] 2020-10-29 08:43
Hi. I am new in graphQL but as I see we need __typename for union types. 
By the way, I am wondering why I can't add  __typename: String! to the input type. then problem should be solved. 
When I add  __typename: String! to the input type, I get an error:
Name "__typename" must not begin with "__", which is reserved by GraphQL introspection.

**Comment by taha-mv** [comment] 2020-11-04 12:07
const client = new ApolloClient({
  link: new HttpLink({uri: MY_URL}),
  cache: new InMemoryCache({
    addTypename: false
  })
});

**Comment by MirrorBytes** [comment] 2020-12-21 17:38
Here's an immutable function that I use for mutations:

```typescript
  function stripTypename<T>(input: T) {
    const newish = { ...input };

    for (const prop in newish) {
      if (prop === '__typename') delete newish[prop];
      else if (typeof newish[prop] === 'object')
        newish[prop] = stripTypename(newish[prop]);
    }

    return newish;
  }
```

Doesn't effect files, doesn't effect caching, doesn't have any extra crap; bare and simple.

**Comment by MirrorBytes** [comment] 2020-12-21 17:50
Here's a basic function I use to strip typename from mutations:

```typescript
  function stripTypename<T>(input: T) {
    const newish = { ...input };

    for (const prop in newish) {
      if (prop === '__typename') delete newish[prop];
      else if (newish[prop] === null) {
      } else if (Array.isArray(newish[prop])) {
        for (const next in newish[prop]) {
          newish[prop][next] = stripTypename(newish[prop][next]);
        }
      } else if (typeof newish[prop] === 'object') {
        newish[prop] = stripTypename(newish[prop]);
      }
    }

    return newish;
  }
```

This doesn't effect files or cache. Might be a bit heavy for larger datasets.

**Comment by anthonysapien** [comment] 2020-12-21 22:22
I found an approach to this that may work for some folks. I started using Yup to define entity schemas for form validation. I'm casting Apollo cache objects to the Yup schema. During casting, there's an option to strip out unknown properties like __typename. I then edit and post the Yup-created object instead of the Apollo cache object. Works great.

**Comment by mmahalwy** [comment] 2020-12-23 10:47
> I found an approach to this that may work for some folks. I started using Yup to define entity schemas for form validation. I'm casting Apollo cache objects to the Yup schema. During casting, there's an option to strip out unknown properties like __typename. I then edit and post the Yup-created object instead of the Apollo cache object. Works great.

@anthonysapien got an example to share?

**Comment by MirrorBytes** [comment] 2020-12-24 20:07
@mmahalwy Here's a way to use a block list with mine:

```typescript
  function stripTypename<T>(input: T, blocklist: string[]) {
    const newish = { ...input };

    for (const prop in newish) {
      if (blocklist.contains(prop)) delete newish[prop];
      else if (newish[prop] === null) {
      } else if (Array.isArray(newish[prop])) {
        for (const next in newish[prop]) {
          newish[prop][next] = stripTypename(newish[prop][next]);
        }
      } else if (typeof newish[prop] === 'object') {
        newish[prop] = stripTypename(newish[prop]);
      }
    }

    return newish;
  }
```

You'd have to manually define the blocklist, but you could also specify the inverse for an allow list if that's easier.

**Comment by anthonysapien** [comment] 2020-12-28 17:53
@mmahalwy here's a short example. 

First, create a schema that can be used to for standalone validation or with a library like Formik.
Then cast the Apollo cache object, and remove unknown properties like __typename.
The example doesn't demonstrate nested entities, but that's works well too.

```javascript
const schema = yup.object().shape({
  id: yup.string(),
  name: yup.string().default('').required('Name is required'),
});

const initialValues = schema.cast(user, { stripUnknown: true });
```

**Comment by mmahalwy** [comment] 2021-01-19 03:14
@anthonysapien that would work but more overkill on the frontend part. Ideally, it's more automatic. Ideally ideally, apollo detects the fields needed to send and only sends those.

**Comment by anthonysapien** [comment] 2021-01-19 20:58
@mmahalwy I agree. It's overkill to solve this problem. Just wanted to share in case others also need validation and want to get past this quickly.

**Comment by jakehewitt** [comment] 2021-02-12 19:36
> Our team is migrating to Apollo, this is a show-stopper.
> 
> Not because of the issue, simply because of the lack of any meaningful response on such a large issue in such a long period. It has dropped our confidence level that Apollo is actually being maintained.

I couldn't agree more, the lack of communication is alarming. Reminds me of the same long standing ignored issues that drove people away from Meteor

**Comment by bryanvaz** [comment] 2021-04-08 17:44
> @anthonysapien that would work but more overkill on the frontend part. Ideally, it's more automatic. Ideally ideally, apollo detects the fields needed to send (as defined from the API in the `input` object) and only sends those.

THIS!

It's what you would expect to happen, otherwise, what is the point of defining an input schema on the client side?

**Comment by Crocsx** [comment] 2021-06-16 09:28
this is still pending here without clear guidelines or good way to implement it, after 3 years.

There are some good solution like using Symbols, ignore additional fields in mutations/queries that are not defined in the schema, or remove __typenames from mutation after the cache used them.

Can we have something official on this ?

**Comment by shivamrsoft** [comment] 2021-07-06 05:30
Is there any generalized solution where this `__typename` can be omitted from the entire application during the update operation.

**Comment by tsadiq** [comment] 2021-07-06 16:17
So, all this conversation (and most of what i found on the web) seems to revolve around `__typename` in query or mutation input but, is there a way to automatically clean-up `__typename` from **results** ? 

I recently joined a project where where have several occurrences of that kind of data structure:
```
interface ThingList {
  keyA: Thing[];
  keyB: Thing[];
  //...
  keyN: Thing[];
}
```
We often need to iterate on every key of `ThingList` and map what's inside. Needless to say, with an additional `__typename: string;` in the middle of our keys we have to check either that the key isn't `__typename`, or that we actually have an array, which is a p in the a when your data structure is meant to be string keys with array value.

I understand this property is used by the caching system but why does it even make it to result data? I don't feel like cleaning my data - especially nested data - every time i query my api or use fetched data. Isn't there a way to tell Apollo to return clean api data instead of polluting it with additional keys?

**Comment by adrianescat** [comment] 2021-08-18 20:06
Hello! waiting for an official update on this too. I have to handle big datasets and solutions posted here with `ApolloLink` fix does not work for me.

**Comment by snemvalts** [comment] 2021-09-07 07:40
Open issue for 3 years to remove an implementation detail from responses...

**Comment by snemvalts** [comment] 2021-09-07 07:46
`addTypename: false`
This silently breaks fragments for me

**Comment by FahmyChaabane** [comment] 2021-09-09 00:44
Hello from 2021 ! 
Isn't any updates for this one ? 
i had found this on google: https://stackoverflow.com/questions/47211778/cleaning-unwanted-fields-from-graphql-responses/51380645#51380645 
i really would like to know if anyone faced issues even after applying this approach.

**Comment by kneczaj-p44** [comment] 2022-02-07 15:20
1) If `__typename` cannot be a field of `input` type, maybe it can be just stripped out when sending it inside the mutation payload? This way we do not remove it, but it is just not messing with mutation calls.
2) I suspect typename is needed for the cache and inside the apollo client. Then we can strip that out when it goes out from apollo-client to react hooks/components.

**Comment by JavaJamie** [comment] 2022-02-10 23:43
This issue has frustrated me for so long. Even urql has a way to mask typenames easily. 

Currently, whenever I do mutations, I omit the __typename from the object and spread the rest of the props and this is what I pass into the mutation. It works fine without issue, but it feels a bit manual.

I haven't added the addTypename prop to the cache because I'm unsure of the consequences and I already find it very flakey as it is.

**Comment by lveillard** [comment] 2022-03-10 03:15
I thought i was doing something wrong doing this manually everytime. I see is old issue. Happy to add my +1 to a symbol solution, or autoremoval on mutation from apolloClient side.

**Comment by shivamrsoft** [comment] 2022-03-10 05:19
Please suggest a solution asap. A lot of developers are facing this issue now.

**Comment by andreujuanc** [comment] 2022-03-18 13:14
To be honest, this should be treated as a BUG. Simply because I queried query{A, B} and somehow I get {A, B, __typename} this is an unwanted field.

**Comment by lveillard** [comment] 2022-03-18 17:25
> To be honest, this should be treated as a BUG. Simply because I queried query{A, B} and somehow I get {A, B, __typename} this is an unwanted field.

Not a bug but the fact that we have to manually remove it or apollo does not accept it for mutations seems like a joke.

**Comment by thebrucecgit** [comment] 2022-04-25 01:01
> Why does the mutation care if there are additional fields in `variables` at all? Can't Apollo Client just use the fields it needs and filter out the rest?

Can we get a response on this query? Why can't the Apollo Client just ignore these additional fields instead of throwing errors?

**Comment by MichaelrMentele** [comment] 2022-05-28 17:27
The stupid and unscalable work around is:
`const { __typename, ...input } = someFormData`

Link seems nice for now, but symbols and the above seem ideal

**Comment by PinkaminaDianePie** [comment] 2022-06-05 16:32
@hwillson @prasek @jpvajda @JakeDawkins

**Comment by tregoning** [comment] 2022-06-07 00:12
In case it helps anybody you can leverage the (not very well known) `replacer` parameter in `JSON.stringify` 

Will remove deeply nested `__typename` fields efficiently from the payload

``` javascript
const cleanPayload = JSON.parse(JSON.stringify(payloadWithTypeName, (name, val) => {
  if (name === '__typename') {
      delete val[name];
  } else {
      return val;
  }
}));
```

**Comment by PinkaminaDianePie** [comment] 2022-06-22 06:52
@hwillson @prasek @jpvajda @JakeDawkins

**Comment by mistermark** [comment] 2022-08-18 13:02
Same issue here, but I've (temporarily) solved this with the solution from @MirrorBytes: https://github.com/apollographql/apollo-feature-requests/issues/6#issuecomment-750966090

Though, I would much prefer to have a native solution to this.

**Comment by SpaceMalamute** [comment] 2022-10-20 15:10
Same issue, when will you fix it?

**Comment by michael-ecklund** [comment] 2022-12-23 04:02
Not exactly a pizza supreme, but it does the trick.... Thought I'd share. ¯\\_(ツ)_/¯

```JavaScript
/**
 * Iterate through an object's properties until all specified properties have been removed.
 *
 * @param theObject
 * @param removeProperties
 * @returns {{}|*}
 */
export function unsetProperties(theObject, removeProperties = []) {
  if (!isObject(theObject) || isEmpty(removeProperties)) {
    return theObject;
  }

  const dataObject = {};

  Object.keys(theObject).map((key) => {
    if (isObject(theObject[key])) {
      dataObject[key] = unsetProperties(theObject[key], removeProperties);
    }

    if (Array.isArray(theObject[key])) {
      dataObject[key] = [];
      theObject[key].map((item) => {
        if (isObject(item)) {
          dataObject[key].push(unsetProperties(item, removeProperties));
        } else {
          dataObject[key].push(item);
        }
        return item;
      });
    }

    if (!isObject(theObject[key]) && !Array.isArray(theObject[key]) && !removeProperties.includes(key)) {
      dataObject[key] = theObject[key];
    }

    return key;
  });

  return dataObject;
}
```

**Comment by livgust** [comment] 2023-02-04 14:34
Adding on to to the pile - this is a total pain.

**Comment by omattman** [comment] 2023-02-22 12:02
+1

**Comment by jerelmiller** [comment] 2023-02-22 21:01
Hey all 👋 

This request seems to have had a _LOT_ of attention over the years. Apologies from the maintainers that we've failed to chime in up to this point. 

There is a lot of history here so I'd like to see if I can restate the ask here to see if I'm understanding this correctly. From what I gather, the issue here seems to be that because Apollo automatically adds the `__typename` field to the GraphQL query document for each request (unless disabled), this causes some headaches when you'd like to use those results as _input_ to a mutation or another query as an argument.

```ts
const QUERY = gql`
  query Book {
    book {
      id
      title
      description
    }
  }
`

const MUTATION = gql`
  mutation UpdateBook(book: Book!) {
    book {
      id
      title
      description
    }
  }
`

const MyComponent = () => {
  const { data } = useQuery(QUERY);
  const [updateBook] = useMutation(MUTATION);

  // ignore the lack of loading/error handling here
  const book = data.book;

  return (
    <button 
      onClick={() => {
        updateBook({ 
          variables: { 
            book: { ...book, description: 'Updated description' }
          }
        });
      }}
    >
      Update book
    </button>;
  );
}
```

Used in this way causes problems because GraphQL inputs don't allow for the use of `__typename` as a field, therefore the mutation fails. 

Does this seem like an accurate reflection of the problem?

---

A bit about the `__typename`. We **STRONGLY** recommend you don't strip these out during the request as the `__typename` is needed for the [cache](https://www.apollographql.com/docs/react/caching/overview) to do its magic. Without the `__typename`, data normalization and other such features such as [type policies](https://www.apollographql.com/docs/react/caching/cache-field-behavior) cease to provide much value since data types are difficult to detect with it. 

I say this to mention that unless there needs to be a VERY compelling reason to build in the ability to easily strip `__typename` from the response where possible.

That being said, if my understanding of the issue as mentioned above is correct, we could consider adding the ability to strip `__typename` automatically during mutations and queries if any `variables` include that field. This however should be fairly easy to implement in user-space with a custom `ApolloLink`:

```ts
const stripTypename = (value) => {
 // ...
}

const stripTypenameLink = new ApolloLink((operation, forward) => {
  const variables = stripTypename(operation.variables);

  return forward({ ...operation, variables })
})
```

--- 

If anyone would be willing to share more details or anything I've missed, that would be much appreciated. Thanks!

**Comment by livgust** [comment] 2023-02-22 21:35
@jerelmiller Yes, that's right. For me, it's happening because I'm getting objects from a query, modifying them, and then sending them back for an update. __typename is still hanging around, so things are failing.

Several people have offered solutions like the pseudocode you pasted above, but there's desire for something official as this seems like a relatively basic feature.

**Comment by jerelmiller** [comment] 2023-02-22 22:10
@livgust awesome, thanks for confirming! This is definitely something I'll chat about with the team to see what makes the most sense. Appreciate it!

**Comment by lveillard** [comment] 2023-03-09 11:43
Yes correct!
If it is not possible to change it by a `Symbol.for('typename')` at least
mutations should not throw an error when receiving the `__typename` props

Il mer 22 feb 2023, 6:10 PM Jerel Miller ***@***.***> ha
scritto:

**Comment by kyleboe** [comment] 2023-04-03 21:17
An implementation thought as I've just recently run into this, an added `includeTypename` boolean configuration setting on [`QueryOptions`](https://github.com/apollographql/apollo-client/blob/main/src/core/watchQueryOptions.ts#L53-L113) (ref: https://www.apollographql.com/docs/react/data/queries#options) might be a small(er), purely additive change to the API.

I believe [your assessment](https://github.com/apollographql/apollo-feature-requests/issues/6#issuecomment-1440791295) of the situation above is 100% accurate where people (myself included) are attempting to pass the results of a query as variables to a mutation. To be able to toggle this setting on an individual query would allow for developers to address this on a case-by-case basis instead of at the client/link level. Just my two cents though. Thanks for keeping after this and let me know if I can assist in any way!

**Comment by jerelmiller** [comment] 2023-04-03 21:37
@kyleboe appreciate the input! 

The biggest problem I have with a setting for the query is that it has downstream effects on caching. Your configured type policies and cache normalization rely on `__typename`, so while its tempting to turn off `__typename` for a single query, you might introduce other problems if your queries rely on the normalized cache.

My current thinking is that we transparently just strip `__typename` fields during any `mutation` operation for you. This allows you to avoid potentially negative side effects on your cache layer, but lets you call mutations freely without the overhead of needing to strip those yourself.

I've got this on the docket as an upcoming item I'd like to take a look at. I'll try and keep this updated as progress is made. Thanks again for the feedback!

**Comment by jerelmiller** [comment] 2023-04-13 22:30
Hey all 👋 I sincerely appreciate the patience on this feature! 

I'm excited to announce that we've merged https://github.com/apollographql/apollo-client/pull/10724 and this feature will be a part of our next minor release `v3.8.0` 🎉 🎉 🎉. We are looking forward to closing out a nearly 5 year old request!

This change will be transparent to you as long as you are using `HttpLink`, `BatchHttpLink` or `GraphQLWsLink`. These links will automatically strip `__typename` fields from `variables` before the request is sent to the server and applies to all operation types (`Query`, `Mutation` and `Subscription`). This should make it much easier to use data from a previous query as input to another query, mutation, or subscription, without the need to remove this field yourself.

---

`v3.8.0` is still in alpha at the time of this writing, so if you'd like to try this out, please do so by installing the alpha release: 

```
npm install @apollo/client@alpha
```

If you have additional feedback or would like to report any bugs related to this feature, please do so by opening an issue in the [`apollo-client`](https://github.com/apollographql/apollo-client) repo for us to track. 

Thanks!

**Closed by jerelmiller** 2023-04-13 22:30 UTC
Labels: project-apollo-client, :link: apollo-link

**Comment by jerelmiller** [comment] 2023-04-14 21:38
Hey all 👋 quick update

We found an issue with the new approach. We strip `__typename` from JSON scalar types unnecessarily and believe these types should be left alone. `__typename` is a valid GraphQL field inside a JSON scalar and there might be valid uses cases to allow this. 

If you have any feedback and would like to chime in on the expected behavior here, please add a comment to https://github.com/apollographql/apollo-client/issues/10767. Thanks!
