### ISSUE TITLE
Pass `extensions` to the client

### ISSUE THREAD

**Issue by bradkrane** [apollographql/apollo-feature-requests#196] opened 2019-12-03 22:19 UTC
Migrated from: apollographql/apollo-client#3613

I'm using Apollo and Node to query a service that in addition to the data I ask for returns an 'extensions' key along with the data. In my case this data contains information on the throttling status of my API key. This key is also returned on a throttling error however this is unavailable in the error response from the Apollo client.

Instead Apollo returns the following in the error response:

```
{
  graphQLErrors: [ { message: 'Throttled' } ],
  networkError: null,
  message: 'GraphQL error: Throttled',
  extraInfo: undefined
}
```
but the error response does also also include the following extensions key that is not made available to the client:
```
"extensions": {
  "cost": {
    "requestedQueryCost": 101,
    "actualQueryCost": 46,
    "throttleStatus": {
      "maximumAvailable": 1000,
      "currentlyAvailable": 954,
      "restoreRate": 50
    }
  }
}
```
Is it possible to configure the Apollo client to pass back all of the keys returns in the response? Thanks!

**Comment by MatthiasKunnen** [comment] 2020-12-18 16:49
Duplicate of #117.

**Comment by jerelmiller** [comment] 2023-04-06 04:55
Closing as a duplicate of #117. Feel free to continue the discussion there!

**Closed by jerelmiller** 2023-04-06 04:55 UTC
Labels: project-apollo-client
