### ISSUE TITLE
Ignore __typename by default in Mutations

### ISSUE THREAD

**Issue by ackvf** [apollographql/apollo-feature-requests#177] opened 2019-09-18 18:10 UTC
Internet is full of `__typename` related problems, workarounds and hacks.
One shouldn't remove it because cache uses it and various other reasons, but you rarely use that in the code. Then feeding that to a form and sending that form data back to server gives errors.

a) Could it be possible that the `__typename` field is ignored in mutations by default - or perhaps make that configurable in ApolloClient.options ?

b) OR allow to use an Afterware that can be applied to all responses to remove the data manually?

**Comment by HosseinAgha** [comment] 2020-01-18 18:22
I think this is the duplicate of #6.

**Comment by andrewmclagan** [comment] 2020-04-15 02:01
The actual issue is being ignored..

**Comment by jerelmiller** [comment] 2023-04-04 23:02
Hey all 👋 

I'm going to close this as a duplicate of #6. If you have any questions/comments, please use that issue. Thanks!

**Closed by jerelmiller** 2023-04-04 23:02 UTC
