### ISSUE TITLE
Strict Equality Of Result Sub-Trees In Deeply Nested Query

### ISSUE THREAD

**Issue by chr1sjf0x** [apollographql/apollo-feature-requests#214] opened 2020-03-02 16:10 UTC
Follow up from [Spectrum Discussion](https://spectrum.chat/apollo/apollo-client/equality-of-deep-sub-trees-3-0-beta~cb164d6c-a414-4478-8eca-f53d76dbb4f4).

If you have a large deeply nested query result like this:
```
{
  things: [
    {
      id: 1000
      name: "thing1",
      deepThings: [ { id: 2000, ... }, ... ]
    },
    {
      id: 1001
      name: "thing2",
      deepThings: [ { id: 2001, ... }, ...  ]
    },
    ... moreThings with nested deepThings
  ];
}
```

And have mutations which act on the `deepThings`. The result of those mutations (or `an optimisticResponse` of those mutations), will result in a change being broadcast on the large query as expected.

However, what was unexpected is that all other `things` and `deepThings` which were not affected by the mutation will not be strictly equal to the original query result.

This results in an unnecessary re-render of a large table of data.

*Workaround* - We avoid the re-render by using React.memo with a deep equality check on the `prevProps` and `nextProps`

I feel it would be nice to have the Apollo Client return strictly equal portions of the larger sub-tree which is unchanged.

However, as I've learned more about the implementation from investigating this issue, that seems like a long shot.

**Comment by stephenh** [comment] 2020-03-16 02:12
It looks like this is a duplicate of the bug report in https://github.com/apollographql/apollo-client/issues/4141.

**Comment by jerelmiller** [comment] 2023-04-06 04:29
Hey @chr1sjf0x 👋 

We will be introducing a [`@nonreactive` directive](https://github.com/apollographql/apollo-client/pull/10722) in v3.8 (currently in alpha) that should help address this performance concern. `@nonreactive` will allow you to mark subtrees in your query as data that should not trigger a rerender. This is meant to be used in conjunction with [`useFragment`](https://www.apollographql.com/docs/react/api/react/hooks-experimental#usefragment_experimental). These features were designed with large lists in mind.

Seeing as this is an upcoming feature, I'm going to go ahead and close this issue as completed. I hope `@nonreactive` serves you well! Please ping us or create a new issue if these new APIs don't adequately address your needs. Thanks!

**Closed by jerelmiller** 2023-04-06 04:29 UTC
